#!/bin/bash
cd "${BASH_SOURCE%/*}" || exit
source nodes_NA.sh 
cli="/home/ubuntu/StakedNotary/komodo/master/komodo-cli -ac_name=TEST1"
echo "$nodes[$1]"
ssh ubuntu@${nodes[$1]} -i blackjok3r_NA.pem "$cli $2 $3 $4 $5 $6 $7 $8 $9"
 
